export const articles = [
  {
    title: 'Strategie de la motivation (partie 1)',
    date: '23 mai 2006',
    content: "Régulièrement, les jugements et analyses que nous portons sur les autres ou nous-mêmes, identifient ce qui semble être une lacune fondamentale, une défaillance apparente de la volonté de l’individu : le manque de motivation. Le désir de se changer soi-même, ou d’aider l’autre à changer, par l’apprentissage de nouveaux savoirs ou techniques, se heurte à des résistances. Les enseignants sont parfois déçus de voir leurs élèves stagner alors qu’ils ont le sentiment de donner le meilleur d’eux-mêmes. Des athlètes désireux d’améliorer leurs performances ne peuvent que constater l’échec de leurs efforts pour progresser. Des parents s’inquiètent de voir leur enfant se désintéresser de l’école. Dans de nombreux domaines (sportifs, professionnels, sentimentaux…), nous constatons souvent, et amèrement, notre propre manque de motivation pour accomplir une tâche. Qu’est-ce qui génère ce manque de motivation? Peut-on considérer que les personnes non motivées sont «naturellement » inaptes? L’autre (ou moi-même), celui qui échoue, a-t-il le « gène de l’échec » en lui? Afin de mieux comprendre ce qui nous préoccupe, il serait plus judicieux de parler de manque de méthode plutôt que de manque de motivation. Car, comme nous allons le voir, la méthode crée la motivation. Ceux qui agissent avec succès ont élaboré, consciemment ou non, une méthode efficace. Il faut en effet établir une stratégie pour toute tentative d’amélioration dans un domaine de notre existence qui a de l’importance pour nous. Mais comment établir une stratégie efficace? Comment faire pour « tenir bon », rester motivé face aux difficultés, à l‘ennui? Qu’est-ce qui fait qu’un enseignement porte rapidement des fruits ou échoue, peinant à faire progresser les élèves? Le texte qui suit a pour objet d’approfondir notre réflexion au travers de l’examen d’un cas particulier : le désir d’améliorer ses capacités athlétiques par la musculation.",
    author: 'Olivier Lafay'
  },
  {
    title: 'Strategie de la motivation (partie 2)',
    date: '25 mai 2006',
    content: "Lutter contre l’Entropie. Notre premier article cherchait à mettre en évidence les rapports existant entre motivation et méthode. Il ressortait de notre analyse que la création d’une méthode efficace exigeait de prendre pour fondation la volonté de vaincre la résistance au changement en développant le sentiment de contrôle. La notion de méthode est différente de celle de stratégie. Il ne faut pas confondre les deux termes. Après les avoir défini, nous allons, en examinant le concept d’entropie, proposer une réflexion sur le concept de « stratégie individuelle ». Cette réflexion ne peut être suffisamment profonde sans avoir compris les notions précédemment élucidées d’homéostasie, de résistance au changement et de sentiment de contrôle. Afin de percevoir les enjeux majeurs d’une telle réflexion, il pourra être utile de relire, au préalable, l’article précédent (Brève analyse des rapports entre motivation et méthode). Commençons par définir méthode et stratégie afin de savoir les différencier. Méthode : ensemble ordonné de manière logique de principes, de règles, d’étapes permettant de parvenir à un résultat.",
    author: 'Olivier Lafay'
  }
]
