export const articles = [
  {
    title: 'Strategie de la motivation (partie 1)',
    date: '23 mai 2006',
    content: "Régulièrement, les jugements et analyses que nous portons sur les autres ou nous-mêmes, identifient ce qui semble être une lacune fondamentale, une défaillance apparente de la volonté de l’individu : le manque de motivation. Le désir de se changer soi-même, ou d’aider l’autre à changer, par l’apprentissage de nouveaux savoirs ou techniques, se heurte à des résistances. Les enseignants sont parfois déçus de voir leurs élèves stagner alors qu’ils ont le sentiment de donner le meilleur d’eux-mêmes. Des athlètes désireux d’améliorer leurs performances ne peuvent que constater l’échec de leurs efforts pour progresser. Des parents s’inquiètent de voir leur enfant se désintéresser de l’école. Dans de nombreux domaines (sportifs, professionnels, sentimentaux…), nous constatons souvent, et amèrement, notre propre manque de motivation pour accomplir une tâche. Qu’est-ce qui génère ce manque de motivation? Peut-on considérer que les personnes non motivées sont «naturellement » inaptes? L’autre (ou moi-même), celui qui échoue, a-t-il le « gène de l’échec » en lui? Afin de mieux comprendre ce qui nous préoccupe, il serait plus judicieux de parler de manque de méthode plutôt que de manque de motivation. Car, comme nous allons le voir, la méthode crée la motivation. Ceux qui agissent avec succès ont élaboré, consciemment ou non, une méthode efficace. Il faut en effet établir une stratégie pour toute tentative d’amélioration dans un domaine de notre existence qui a de l’importance pour nous. Mais comment établir une stratégie efficace? Comment faire pour « tenir bon », rester motivé face aux difficultés, à l‘ennui? Qu’est-ce qui fait qu’un enseignement porte rapidement des fruits ou échoue, peinant à faire progresser les élèves? Le texte qui suit a pour objet d’approfondir notre réflexion au travers de l’examen d’un cas particulier : le désir d’améliorer ses capacités athlétiques par la musculation.",
    author: 'Olivier Lafay',
    image: 'https://olivier-lafay.com/app/uploads/2019/03/faire-camino-santiago-hiver.jpg',
  },
  {
    title: 'Strategie de la motivation (partie 2)',
    date: '25 mai 2006',
    content: "Lutter contre l’Entropie. Notre premier article cherchait à mettre en évidence les rapports existant entre motivation et méthode. Il ressortait de notre analyse que la création d’une méthode efficace exigeait de prendre pour fondation la volonté de vaincre la résistance au changement en développant le sentiment de contrôle. La notion de méthode est différente de celle de stratégie. Il ne faut pas confondre les deux termes. Après les avoir défini, nous allons, en examinant le concept d’entropie, proposer une réflexion sur le concept de « stratégie individuelle ». Cette réflexion ne peut être suffisamment profonde sans avoir compris les notions précédemment élucidées d’homéostasie, de résistance au changement et de sentiment de contrôle. Afin de percevoir les enjeux majeurs d’une telle réflexion, il pourra être utile de relire, au préalable, l’article précédent (Brève analyse des rapports entre motivation et méthode). Commençons par définir méthode et stratégie afin de savoir les différencier. Méthode : ensemble ordonné de manière logique de principes, de règles, d’étapes permettant de parvenir à un résultat.",
    author: 'Olivier Lafay',
    image: 'https://olivier-lafay.com/app/uploads/2019/01/23537-300x300.jpg'
  },
  {
    title: "Répéter jusqu’à en mourir",
    date: '18 Janvier 2012',
    content: "Freud parle de “compulsion de répétition”, Levine parle de “remise en actes”, Watzlawick parle de “toujours plus de la même chose”. On pourrait également citer Karli, Lipton, Selye, Rossi, etc, qui tous ont abordé ce sujet à leur manière. Il s’agit de notre tendance à vouloir répéter une situation (où nous avons été mis en difficulté) aussi souvent que possible, en espérant, au final, gagner. C’est un processus inconscient, qui s’appuie sur des racines animales profondes.Le savoir permet de chercher d’autres voies. Ne pas le savoir, c’est s’agenouiller, s’humilier en pensant combattre : revenir sans cesse sur une confrontation où l’on a été vaincu, en espérant remporter, au final, l’affaire. Tout cela en faisant dans la surenchère à chaque fois, en se disant que si la stratégie a échoué jusque là, c’est que l’on n’en a pas assez fait. Incapable de se dire que, si l’on a échoué, c’est uniquement parce que la stratégie est mauvaise. Mais ceux qui sont pris dans cet engrenage ne le peuvent, car leur horizon limité (manque de recul critique) ne leur permet que cette stratégie. C’est donc un serpent qui se mord la queue de plus en plus fort… C’est la mouche qui bute sans cesse contre la vitre, alors qu’un léger vol latéral de quelques cm lui permettrait d’envisager la sortie, là où la fenêtre est légèrement ouverte. L’image est donc celle d’un cercle infernal dont il faut sortir, et cela se fait en étant créatif, ouvert, en réfléchissant à nos conditionnements.  Mes articles de fond sur le blog ont pour objet d’apporter des éléments permettant de dépasser ces situations. Car sortir d’un cercle infernal, c’est pouvoir progresser de manière générale, et pas seulement en musculation. Cela évitera ainsi la monomanie (type bodybuilding obsessionnel) et le dopage (qui est l’outil “salvateur” de ceux qui butent sur un mur, de manière répétitive, en pensant qu’il est physiologique, alors que c’est bien plus que ça). Cela évitera les blessures à répétition, les agressions haineuses compulsives qui rendent esclave de celui que l’on hait et qui étouffent la créativité. Quand un problème se pose en musculation, l’erreur est de chercher sa solution uniquement dans le domaine spécifique de la musculation.",
    author: 'Olivier Lafay',
    image: 'https://olivier-lafay.com/app/uploads/2012/01/1460.jpg'
  }
]
